config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [ :new, :create ]
  end
  # Defines the root path route ("/")
  # root "articles#index"
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates_length_of :comment, minimum: 6
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already here"}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    # raise
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
    redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  private

  def set_lists
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/new.html.erb
<p>movie list</p>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <div class="form-inputs">
    <%= f.input :comment %>
    <%= f.association :movie %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div>
  <p>
    <strong>Name:</strong>
    <%= list.name %>
  </p>

  <p>
    <strong>poster url:</strong>
    <%# <%= list.poster_url %>
  </p> %>

</div>

app/views/lists/index.html.erb
<p>whateverrr</p>
<div class="banner">
  <div class="container">
    <h1>The List</strong></h1>
  </div>
</div>


<div id="lists" class="container">
  <% @lists.each do |list| %>
    <%= link_to list.name, list_path(list) %>

  <% end %>
</div>
<div class="text-center">
  <%= link_to "New list", new_list_path, class: "btn btn-primary mb-5" %>
</div>

app/views/lists/new.html.erb
<h1>Add a new list</h1>

<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @list %>

<div class="text-center">
  <%# <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Back to lists", lists_path %> %>
  <%= button_to "Destroy this list", @list, method: :delete, class: "btn btn-danger mt-1" %>
</div>

<div class="movie-container">
  <% @list.movies.each do |movie| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= movie.movie_poster_url %>)">
      <%= movie.name %>
      <%= movie.poster_url %>
      <%= image_tag movie.poster_url %>
    </div>

  <% end %>
</div>

<%= link_to "add new movie", new_list_bookmark_path(@list), class:"btn btn-primary" %>